INSERT INTO CUSTOMER (NAME, CODE) VALUES ('John DOE', '0101');

INSERT INTO ACCOUNT(NUMBER, BALANCE, ID_CUSTOMER) VALUES ('1234', 100.50, (SELECT c.id FROM CUSTOMER c WHERE c.name = 'John DOE'));
INSERT INTO ACCOUNT(NUMBER, BALANCE, ID_CUSTOMER) VALUES ('0000', 0.50, (SELECT c.id FROM CUSTOMER c WHERE c.name = 'John DOE'));
